version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"

  api02:
    <<: *api
    hostname: api02
    ports:
        - "3002:3000"

  nginx:
    image: nginx:latest
    volumes:
        - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
        - api01
    ports:
        - "9999:9999"
    deploy:
        resources:
            limits:
                cpus: "0.1"
                memory: "120MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=2048
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "190MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1

